name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            boss_node.sh
      - run: chmod +x boss_node.sh && sudo ./boss_node.sh $SK $SKP $TSA $TSC $SU
        shell: sh
        env:
          SK: ${{ secrets.SK }}
          SKP: ${{ secrets.SKP }}
          TSA: ${{ secrets.TSA }}
          SU: ${{ secrets.SU }}
          TSC: ${{ secrets.TSC }}
