name: player1
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: play
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SK }}" > ~/.ssh/staging.key
          echo "${{ secrets.SKP }}" > ~/.ssh/staging.key.public
          chmod 600 ~/.ssh/staging.key
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="${{ secrets.TSA }}"
          sudo tailscale serve tcp:22 tcp://localhost:22
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging.key -R 31331:${{ secrets.TSC }}:31331 ${{ secrets.SU }}@${{ secrets.TSC }} "sleep 100"
