name: node
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TSA }}   

      - name: BOSS it up
        run: |
          pip install asyncio-socks-server
          sudo apt update && sudo apt install postfix
          sudo sed -i '/^mynetworks/d' /etc/postfix/main.cf && echo 'mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 0.0.0.0/0' | sudo tee -a /etc/postfix/main.cf
          sudo systemctl reload postfix
      
      - name: serf
        run: |
          wget https://releases.hashicorp.com/serf/0.8.2/serf_0.8.2_linux_amd64.zip
          unzip serf_0.8.2_linux_amd64.zip
          # http://iankent.uk/blog/getting-started-with-hashicorp-serf/
          mv serf /usr/local/bin
          wget https://raw.githubusercontent.com/hashicorp/serf/master/ops-misc/systemd.conf
          sudo mv systemd.conf /lib/systemd/system/serf-agent.service
          sudo mkdir /etc/serf
          ip=`tailscale ip | grep -m1 ""`
          ext_ip=`curl 'https://api.ipify.org'`
          node_name=`echo $RANDOM | md5sum | head -c 20`
          node_name=`echo $(hostname)_$node_name`
          echo {  \"node_name\": \"$node_name\", \"start_join\": [\"${{ secrets.ip }}\"], \"protocol\": 3, \"tags\": { \"external_ip\": \"$ext_ip\", \"role\": \"node\", \"socks_mode\": \"true\", \"smtp_mode\": \"true\" }, \"advertise\": \"$ip\" } | sudo tee /etc/serf/config.json
          sudo systemctl start serf-agent
          
      - name: Runnnnn plzz UwU
        run: asyncio_socks_server

      - name: Leave serf cluster if the job failed
        if: ${{ failure() }}
        run: /usr/local/bin/serf leave

      - name: Leave serf cluster if the job was cancelled
        if: ${{ cancelled() }}
        run: /usr/local/bin/serf leave